from __future__ import annotations

from .data_pedagogy_5_8 import (
    CLASSIFIER_BY_CODE,
    PEDAGOGY_5_8_CLASSIFIER,
    PROFILE_MIN_SCORE,
    PROFILE_SELECTION_LIMIT,
    PROFILE_SELECTION_SESSION_KEY,
    ClassifierItem,
)

THEMATIC_CLASSIFIER = PEDAGOGY_5_8_CLASSIFIER
